// Spectrum word pairs for Wavelength game
export const SPECTRUM_PAIRS = [
  { left: "Good for you", right: "Bad for you" },
  { left: "Highly addictive", right: "Not addictive" },
  { left: "Cold to touch", right: "Hot to touch" },
  { left: "Colorful", right: "Colorless" },
  { left: "High calorie food", right: "Low calorie food" },
  { left: "Essential to live", right: "Inessential to live" },
  { left: "Expensive thing to own", right: "Cheap thing to own" },
  { left: "Overrated weapon in a zombie apocalypse", right: "Underrated weapon in a zombie apocalypse" },
  { left: "Common thing to own", right: "Rare thing to own" },
  { left: "Hard subject at school", right: "Easy subject at school" },
  { left: "Easy to use", right: "Difficult to use" },
  { left: "Requires skill", right: "Requires luck" },
  { left: "Flavorful food", right: "Flavorless food" },
  { left: "Fascinating topic", right: "Boring topic" },
  { left: "Safe job", right: "Dangerous job" },
  { left: "Formal event", right: "Casual event" },
  { left: "Overpaid job", right: "Underpaid job" },
  { left: "Overrated skill", right: "Underrated skill" },
  { left: "Encouraged to do", right: "Forbidden to do" },
  { left: "Durable item", right: "Fragile item" },
  { left: "Best day of the year", right: "Worst day of the year" },
  { left: "Good habit", right: "Bad habit" },
  { left: "Easy thing to find", right: "Hard thing to find" },
  { left: "Easy to remember", right: "Hard to remember" },
  { left: "Healthy food", right: "Unhealthy food" },
  { left: "Historically irrelevant", right: "Historically important" },
  { left: "Hairy animal", right: "Hairless animal" },
  { left: "Exotic pet", right: "Normal pet" },
  { left: "Movie was better", right: "Book was better" },
  { left: "Good movie", right: "Bad movie" },
  { left: "Happens suddenly", right: "Happens slowly" },
  { left: "Hated by many", right: "Loved by many" },
  { left: "Good pizza topping", right: "Bad pizza topping" },
  { left: "Overrated thing to own", right: "Underrated thing to own" },
  { left: "Physical activity", right: "Mental activity" },
  { left: "Mandatory activity", right: "Optional activity" },
  { left: "Overrated letter of the alphabet", right: "Underrated letter of the alphabet" },
  { left: "Easy to pronounce", right: "Hard to pronounce" },
  { left: "High quality", right: "Low quality" },
  { left: "Has a good reputation", right: "Has a bad reputation" },
  { left: "Well made", right: "Poorly made" },
  { left: "Loud place", right: "Quiet place" },
  { left: "Safe place", right: "Dangerous place" },
  { left: "Culturally insignificant", right: "Culturally significant" },
  { left: "Irreplaceable", right: "Replaceable" },
  { left: "Greatest athlete", right: "Worst athlete" },
  { left: "Useful major", right: "Useless major" },
  { left: "Smooth surface", right: "Rough surface" },
  { left: "Good use of time", right: "Waste of time" },
  { left: "Nice animal", right: "Scary animal" },
  { left: "Everybody does it", right: "Nobody does it" },
  { left: "Smells good", right: "Smells bad" },
  { left: "Meal", right: "Snack" },
  { left: "Most evil company", right: "Least evil company" },
  { left: "Hard", right: "Soft" },
  { left: "Better cold", right: "Better hot" },
  { left: "Good superpower", right: "Bad superpower" },
  { left: "Effective", right: "Ineffective" },
  { left: "Believable", right: "Unbelievable" },
  { left: "Permanent", right: "Temporary" },
  { left: "Tastes good", right: "Tastes bad" },
  { left: "Clean food", right: "Messy food" },
  { left: "Good gift", right: "Bad gift" },
  { left: "Fashionable", right: "Unfashionable" },
  { left: "Hygienic", right: "Unhygienic" },
  { left: "Useful", right: "Useless" },
  { left: "Important", right: "Unimportant" },
  { left: "Hard to spell", right: "Easy to spell" },
  { left: "Popular activity", right: "Unpopular activity" },
  { left: "Reliable", right: "Unreliable" },
  { left: "Traditionally feminine", right: "Traditionally masculine" },
  { left: "Useful body part", right: "Useless body part" },
  { left: "Strong animal", right: "Weak animal" },
  { left: "Useful invention", right: "Useless invention" },
  { left: "Popular", right: "Unpopular" },
  { left: "Exciting activity", right: "Boring activity" },
  { left: "Smelly in a good way", right: "Smelly in a bad way" },
  { left: "Useful in an emergency", right: "Useless in an emergency" },
  { left: "For adults", right: "For kids" },
  { left: "Hard to do", right: "Easy to do" },
  { left: "Priceless", right: "Worthless" },
  { left: "Weird greeting", right: "Normal greeting" },
  { left: "Infinite", right: "Limited" },
  { left: "Good investment", right: "Bad investment" },
  { left: "Spicy food", right: "Mild food" },
  { left: "Loud sound", right: "Quiet sound" },
  { left: "Public knowledge", right: "Secret" },
  { left: "Too big to hold", right: "Too small to hold" },
  { left: "Long time to travel", right: "Short time to travel" },
  { left: "Best year in history", right: "Worst year in history" },
  { left: "Well known fact", right: "Little known fact" },
  { left: "Global issue", right: "Local issue" },
  { left: "Best era to time travel", right: "Worst era to time travel" },
  { left: "Large number", right: "Small number" },
  { left: "Beautiful word", right: "Ugly word" },
  { left: "Natural ", right: "Unnatural" },
  { left: "Original", right: "Derivative" },
  { left: "Too much of something", right: "Not enough of something" },
  { left: "Good dog breed", right: "Bad dog breed" },
  { left: "Good advice", right: "Bad advice" },
  { left: "Good candy", right: "Bad candy" },
  { left: "Morning time activity", right: "Night time activity" },
  { left: "Big number", right: "Small number" },
  { left: "Fast Marathon time", right: "Slow Marathon time" },
  { left: "Close to Earth", right: "Far from Earth" },
  { left: "Easy to learn", right: "Hard to learn" },
  { left: "Cheap thing", right: "Expensive thing" },
  { left: "Old thing", right: "New thing" },
  { left: "Solo activity", right: "Group activity" },
  { left: "Short walk", right: "Long walk" },
  { left: "Short distance to drive", right: "Long distance to drive" },
  { left: "Simple to assemble", right: "Complex to assemble" },
  { left: "Naturally occurring", right: "Artificially created" },
  { left: "Indoor activity", right: "Outdoor activity" },
  { left: "Modern place", right: "Ancient place" },
];

// Helper function to get a random spectrum pair
export function getRandomSpectrumPair() {
  const randomIndex = Math.floor(Math.random() * SPECTRUM_PAIRS.length);
  return SPECTRUM_PAIRS[randomIndex];
}
